<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Region;

class RegenciesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Region::insert(
            [
                ["province_id" => 1, "name" => "Kabupaten Simeulue", "kode_kabupaten_kota" => "1101"],
                ["province_id" => 1, "name" => "Kabupaten Aceh Singkil", "kode_kabupaten_kota" => "1102"],
                ["province_id" => 1, "name" => "Kabupaten Aceh Selatan", "kode_kabupaten_kota" => "1103"],
                ["province_id" => 1, "name" => "Kabupaten Aceh Tenggara", "kode_kabupaten_kota" => "1104"],
                ["province_id" => 1, "name" => "Kabupaten Aceh Timur", "kode_kabupaten_kota" => "1105"],
                ["province_id" => 1, "name" => "Kabupaten Aceh Tengah", "kode_kabupaten_kota" => "1106"],
                ["province_id" => 1, "name" => "Kabupaten Aceh Barat", "kode_kabupaten_kota" => "1107"],
                ["province_id" => 1, "name" => "Kabupaten Aceh Besar", "kode_kabupaten_kota" => "1108"],
                ["province_id" => 1, "name" => "Kabupaten Pidie", "kode_kabupaten_kota" => "1109"],
                ["province_id" => 1, "name" => "Kabupaten Bireuen", "kode_kabupaten_kota" => "1110"],
                ["province_id" => 1, "name" => "Kabupaten Aceh Utara", "kode_kabupaten_kota" => "1111"],
                ["province_id" => 1, "name" => "Kabupaten Aceh Barat Daya", "kode_kabupaten_kota" => "1112"],
                ["province_id" => 1, "name" => "Kabupaten Gayo Lues", "kode_kabupaten_kota" => "1113"],
                ["province_id" => 1, "name" => "Kabupaten Aceh Tamiang", "kode_kabupaten_kota" => "1114"],
                ["province_id" => 1, "name" => "Kabupaten Nagan Raya", "kode_kabupaten_kota" => "1115"],
                ["province_id" => 1, "name" => "Kabupaten Aceh Jaya", "kode_kabupaten_kota" => "1116"],
                ["province_id" => 1, "name" => "Kabupaten Bener Meriah", "kode_kabupaten_kota" => "1117"],
                ["province_id" => 1, "name" => "Kabupaten Pidie Jaya", "kode_kabupaten_kota" => "1118"],
                ["province_id" => 1, "name" => "Kota Banda Aceh", "kode_kabupaten_kota" => "1171"],
                ["province_id" => 1, "name" => "Kota Sabang", "kode_kabupaten_kota" => "1172"],
                ["province_id" => 1, "name" => "Kota Langsa", "kode_kabupaten_kota" => "1173"],
                ["province_id" => 1, "name" => "Kota Lhokseumawe", "kode_kabupaten_kota" => "1174"],
                ["province_id" => 1, "name" => "Kota Subulussalam", "kode_kabupaten_kota" => "1175"],

                ["province_id" => 2, "name" => "Kabupaten Nias", "kode_kabupaten_kota" => "1201"],
                ["province_id" => 2, "name" => "Kabupaten Mandailing Natal", "kode_kabupaten_kota" => "1202"],
                ["province_id" => 2, "name" => "Kabupaten Tapanuli Selatan", "kode_kabupaten_kota" => "1203"],
                ["province_id" => 2, "name" => "Kabupaten Tapanuli Tengah", "kode_kabupaten_kota" => "1204"],
                ["province_id" => 2, "name" => "Kabupaten Tapanuli Utara", "kode_kabupaten_kota" => "1205"],
                ["province_id" => 2, "name" => "Kabupaten Toba", "kode_kabupaten_kota" => "1206"],
                ["province_id" => 2, "name" => "Kabupaten Labuhan Batu", "kode_kabupaten_kota" => "1207"],
                ["province_id" => 2, "name" => "Kabupaten Asahan", "kode_kabupaten_kota" => "1208"],
                ["province_id" => 2, "name" => "Kabupaten Simalungun", "kode_kabupaten_kota" => "1209"],
                ["province_id" => 2, "name" => "Kabupaten Dairi", "kode_kabupaten_kota" => "1210"],
                ["province_id" => 2, "name" => "Kabupaten Karo", "kode_kabupaten_kota" => "1211"],
                ["province_id" => 2, "name" => "Kabupaten Deli Serdang", "kode_kabupaten_kota" => "1212"],
                ["province_id" => 2, "name" => "Kabupaten Langkat", "kode_kabupaten_kota" => "1213"],
                ["province_id" => 2, "name" => "Kabupaten Nias Selatan", "kode_kabupaten_kota" => "1214"],
                ["province_id" => 2, "name" => "Kabupaten Humbang Hasundutan", "kode_kabupaten_kota" => "1215"],
                ["province_id" => 2, "name" => "Kabupaten Pakpak Bharat", "kode_kabupaten_kota" => "1216"],
                ["province_id" => 2, "name" => "Kabupaten Samosir", "kode_kabupaten_kota" => "1217"],
                ["province_id" => 2, "name" => "Kabupaten Serdang Bedagai", "kode_kabupaten_kota" => "1218"],
                ["province_id" => 2, "name" => "Kabupaten Batu Bara", "kode_kabupaten_kota" => "1219"],
                ["province_id" => 2, "name" => "Kabupaten Padang Lawas Utara", "kode_kabupaten_kota" => "1220"],
                ["province_id" => 2, "name" => "Kabupaten Padang Lawas", "kode_kabupaten_kota" => "1221"],
                ["province_id" => 2, "name" => "Kabupaten Labuhan Batu Selatan", "kode_kabupaten_kota" => "1222"],
                ["province_id" => 2, "name" => "Kabupaten Labuhan Batu Utara", "kode_kabupaten_kota" => "1223"],
                ["province_id" => 2, "name" => "Kabupaten Nias Utara", "kode_kabupaten_kota" => "1224"],
                ["province_id" => 2, "name" => "Kabupaten Nias Barat", "kode_kabupaten_kota" => "1225"],

                // KOTA
                ["province_id" => 2, "name" => "Kota Sibolga", "kode_kabupaten_kota" => "1271"],
                ["province_id" => 2, "name" => "Kota Tanjung Balai", "kode_kabupaten_kota" => "1272"],
                ["province_id" => 2, "name" => "Kota Pematang Siantar", "kode_kabupaten_kota" => "1273"],
                ["province_id" => 2, "name" => "Kota Tebing Tinggi", "kode_kabupaten_kota" => "1274"],
                ["province_id" => 2, "name" => "Kota Medan", "kode_kabupaten_kota" => "1275"],
                ["province_id" => 2, "name" => "Kota Binjai", "kode_kabupaten_kota" => "1276"],
                ["province_id" => 2, "name" => "Kota Padangsidimpuan", "kode_kabupaten_kota" => "1277"],
                ["province_id" => 2, "name" => "Kota Gunungsitoli", "kode_kabupaten_kota" => "1278"],

                ["province_id" => 3, "name" => "Kabupaten Pesisir Selatan", "kode_kabupaten_kota" => "1301"],
                ["province_id" => 3, "name" => "Kabupaten Solok", "kode_kabupaten_kota" => "1302"],
                ["province_id" => 3, "name" => "Kabupaten Sijunjung", "kode_kabupaten_kota" => "1303"],
                ["province_id" => 3, "name" => "Kabupaten Tanah Datar", "kode_kabupaten_kota" => "1304"],
                ["province_id" => 3, "name" => "Kabupaten Padang Pariaman", "kode_kabupaten_kota" => "1305"],
                ["province_id" => 3, "name" => "Kabupaten Agam", "kode_kabupaten_kota" => "1306"],
                ["province_id" => 3, "name" => "Kabupaten Lima Puluh Kota", "kode_kabupaten_kota" => "1307"],
                ["province_id" => 3, "name" => "Kabupaten Pasaman", "kode_kabupaten_kota" => "1308"],
                ["province_id" => 3, "name" => "Kabupaten Solok Selatan", "kode_kabupaten_kota" => "1309"],
                ["province_id" => 3, "name" => "Kabupaten Dharmasraya", "kode_kabupaten_kota" => "1310"],
                ["province_id" => 3, "name" => "Kabupaten Pasaman Barat", "kode_kabupaten_kota" => "1311"],
                ["province_id" => 3, "name" => "Kota Padang", "kode_kabupaten_kota" => "1371"],
                ["province_id" => 3, "name" => "Kota Solok", "kode_kabupaten_kota" => "1372"],
                ["province_id" => 3, "name" => "Kota Sawah Lunto", "kode_kabupaten_kota" => "1373"],
                ["province_id" => 3, "name" => "Kota Padang Panjang", "kode_kabupaten_kota" => "1374"],
                ["province_id" => 3, "name" => "Kota Bukittinggi", "kode_kabupaten_kota" => "1375"],
                ["province_id" => 3, "name" => "Kota Payakumbuh", "kode_kabupaten_kota" => "1376"],
                ["province_id" => 3, "name" => "Kota Pariaman", "kode_kabupaten_kota" => "1377"],

                ["province_id" => 4, "name" => "Kabupaten Kuantan Singingi", "kode_kabupaten_kota" => "1401"],
                ["province_id" => 4, "name" => "Kabupaten Indragiri Hulu", "kode_kabupaten_kota" => "1402"],
                ["province_id" => 4, "name" => "Kabupaten Indragiri Hilir", "kode_kabupaten_kota" => "1403"],
                ["province_id" => 4, "name" => "Kabupaten Pelalawan", "kode_kabupaten_kota" => "1404"],
                ["province_id" => 4, "name" => "Kabupaten Siak", "kode_kabupaten_kota" => "1405"],
                ["province_id" => 4, "name" => "Kabupaten Kampar", "kode_kabupaten_kota" => "1406"],
                ["province_id" => 4, "name" => "Kabupaten Rokan Hulu", "kode_kabupaten_kota" => "1407"],
                ["province_id" => 4, "name" => "Kabupaten Bengkalis", "kode_kabupaten_kota" => "1408"],
                ["province_id" => 4, "name" => "Kabupaten Rokan Hilir", "kode_kabupaten_kota" => "1409"],
                ["province_id" => 4, "name" => "Kabupaten Kepulauan Meranti", "kode_kabupaten_kota" => "1410"],
                ["province_id" => 4, "name" => "Kota Pekanbaru", "kode_kabupaten_kota" => "1471"],
                ["province_id" => 4, "name" => "Kota Dumai", "kode_kabupaten_kota" => "1472"],

                ["province_id" => 5, "name" => "Kabupaten Kerinci", "kode_kabupaten_kota" => "1501"],
                ["province_id" => 5, "name" => "Kabupaten Merangin", "kode_kabupaten_kota" => "1502"],
                ["province_id" => 5, "name" => "Kabupaten Sarolangun", "kode_kabupaten_kota" => "1503"],
                ["province_id" => 5, "name" => "Kabupaten Batang Hari", "kode_kabupaten_kota" => "1504"],
                ["province_id" => 5, "name" => "Kabupaten Muaro Jambi", "kode_kabupaten_kota" => "1505"],
                ["province_id" => 5, "name" => "Kabupaten Tanjung Jabung Timur", "kode_kabupaten_kota" => "1506"],
                ["province_id" => 5, "name" => "Kabupaten Tanjung Jabung Barat", "kode_kabupaten_kota" => "1507"],
                ["province_id" => 5, "name" => "Kabupaten Tebo", "kode_kabupaten_kota" => "1508"],
                ["province_id" => 5, "name" => "Kabupaten Bungo", "kode_kabupaten_kota" => "1509"],
                ["province_id" => 5, "name" => "Kota Jambi", "kode_kabupaten_kota" => "1571"],
                ["province_id" => 5, "name" => "Kota Sungai Penuh", "kode_kabupaten_kota" => "1572"],

                ["province_id" => 6, "name" => "Kabupaten Ogan Komering Ulu", "kode_kabupaten_kota" => "1601"],
                ["province_id" => 6, "name" => "Kabupaten Ogan Komering Ilir", "kode_kabupaten_kota" => "1602"],
                ["province_id" => 6, "name" => "Kabupaten Muara Enim", "kode_kabupaten_kota" => "1603"],
                ["province_id" => 6, "name" => "Kabupaten Lahat", "kode_kabupaten_kota" => "1604"],
                ["province_id" => 6, "name" => "Kabupaten Musi Rawas", "kode_kabupaten_kota" => "1605"],
                ["province_id" => 6, "name" => "Kabupaten Musi Banyuasin", "kode_kabupaten_kota" => "1606"],
                ["province_id" => 6, "name" => "Kabupaten Banyuasin", "kode_kabupaten_kota" => "1607"],
                ["province_id" => 6, "name" => "Kabupaten Ogan Komering Ulu Selatan", "kode_kabupaten_kota" => "1608"],
                ["province_id" => 6, "name" => "Kabupaten Ogan Komering Ulu Timur", "kode_kabupaten_kota" => "1609"],
                ["province_id" => 6, "name" => "Kabupaten Ogan Ilir", "kode_kabupaten_kota" => "1610"],
                ["province_id" => 6, "name" => "Kabupaten Empat Lawang", "kode_kabupaten_kota" => "1611"],
                ["province_id" => 6, "name" => "Kabupaten Penukal Abab Lematang Ilir", "kode_kabupaten_kota" => "1612"],
                ["province_id" => 6, "name" => "Kota Palembang", "kode_kabupaten_kota" => "1671"],
                ["province_id" => 6, "name" => "Kota Prabumulih", "kode_kabupaten_kota" => "1672"],
                ["province_id" => 6, "name" => "Kota Pagar Alam", "kode_kabupaten_kota" => "1673"],
                ["province_id" => 6, "name" => "Kota Lubuklinggau", "kode_kabupaten_kota" => "1674"],

                ["province_id" => 7, "name" => "Kabupaten Bengkulu Selatan", "kode_kabupaten_kota" => "1701"],
                ["province_id" => 7, "name" => "Kabupaten Rejang Lebong", "kode_kabupaten_kota" => "1702"],
                ["province_id" => 7, "name" => "Kabupaten Bengkulu Utara", "kode_kabupaten_kota" => "1703"],
                ["province_id" => 7, "name" => "Kabupaten Kaur", "kode_kabupaten_kota" => "1704"],
                ["province_id" => 7, "name" => "Kabupaten Seluma", "kode_kabupaten_kota" => "1705"],
                ["province_id" => 7, "name" => "Kabupaten Mukomuko", "kode_kabupaten_kota" => "1706"],
                ["province_id" => 7, "name" => "Kabupaten Lebong", "kode_kabupaten_kota" => "1707"],
                ["province_id" => 7, "name" => "Kabupaten Kepahiang", "kode_kabupaten_kota" => "1708"],
                ["province_id" => 7, "name" => "Kabupaten Bengkulu Tengah", "kode_kabupaten_kota" => "1709"],
                ["province_id" => 7, "name" => "Kota Bengkulu", "kode_kabupaten_kota" => "1771"],

                ["province_id" => 8, "name" => "Kabupaten Lampung Barat", "kode_kabupaten_kota" => "1801"],
                ["province_id" => 8, "name" => "Kabupaten Tanggamus", "kode_kabupaten_kota" => "1802"],
                ["province_id" => 8, "name" => "Kabupaten Lampung Selatan", "kode_kabupaten_kota" => "1803"],
                ["province_id" => 8, "name" => "Kabupaten Lampung Timur", "kode_kabupaten_kota" => "1804"],
                ["province_id" => 8, "name" => "Kabupaten Lampung Tengah", "kode_kabupaten_kota" => "1805"],
                ["province_id" => 8, "name" => "Kabupaten Lampung Utara", "kode_kabupaten_kota" => "1806"],
                ["province_id" => 8, "name" => "Kabupaten Way Kanan", "kode_kabupaten_kota" => "1807"],
                ["province_id" => 8, "name" => "Kabupaten Tulang Bawang", "kode_kabupaten_kota" => "1808"],
                ["province_id" => 8, "name" => "Kabupaten Pesawaran", "kode_kabupaten_kota" => "1809"],
                ["province_id" => 8, "name" => "Kabupaten Pringsewu", "kode_kabupaten_kota" => "1810"],
                ["province_id" => 8, "name" => "Kabupaten Mesuji", "kode_kabupaten_kota" => "1811"],
                ["province_id" => 8, "name" => "Kabupaten Tulang Bawang Barat", "kode_kabupaten_kota" => "1812"],
                ["province_id" => 8, "name" => "Kota Bandar Lampung", "kode_kabupaten_kota" => "1871"],
                ["province_id" => 8, "name" => "Kota Metro", "kode_kabupaten_kota" => "1872"],

                ["province_id" => 9, "name" => "Kabupaten Bangka", "kode_kabupaten_kota" => "1901"],
                ["province_id" => 9, "name" => "Kabupaten Belitung", "kode_kabupaten_kota" => "1902"],
                ["province_id" => 9, "name" => "Kabupaten Bangka Barat", "kode_kabupaten_kota" => "1903"],
                ["province_id" => 9, "name" => "Kabupaten Bangka Tengah", "kode_kabupaten_kota" => "1904"],
                ["province_id" => 9, "name" => "Kabupaten Bangka Selatan", "kode_kabupaten_kota" => "1905"],
                ["province_id" => 9, "name" => "Kabupaten Belitung Timur", "kode_kabupaten_kota" => "1906"],
                ["province_id" => 9, "name" => "Kota Pangkal Pinang", "kode_kabupaten_kota" => "1971"],

                ["province_id" => 10, "name" => "Kabupaten Karimun", "kode_kabupaten_kota" => "2101"],
                ["province_id" => 10, "name" => "Kabupaten Bintan", "kode_kabupaten_kota" => "2102"],
                ["province_id" => 10, "name" => "Kabupaten Natuna", "kode_kabupaten_kota" => "2103"],
                ["province_id" => 10, "name" => "Kabupaten Lingga", "kode_kabupaten_kota" => "2104"],
                ["province_id" => 10, "name" => "Kabupaten Kepulauan Anambas", "kode_kabupaten_kota" => "2105"],
                ["province_id" => 10, "name" => "Kota Batam", "kode_kabupaten_kota" => "2171"],
                ["province_id" => 10, "name" => "Kota Tanjung Pinang", "kode_kabupaten_kota" => "2172"],

                ["province_id" => 11, "name" => "Kabupaten Bogor", "kode_kabupaten_kota" => "3201"],
                ["province_id" => 11, "name" => "Kabupaten Sukabumi", "kode_kabupaten_kota" => "3202"],
                ["province_id" => 11, "name" => "Kabupaten Cianjur", "kode_kabupaten_kota" => "3203"],
                ["province_id" => 11, "name" => "Kabupaten Bandung", "kode_kabupaten_kota" => "3204"],
                ["province_id" => 11, "name" => "Kabupaten Garut", "kode_kabupaten_kota" => "3205"],
                ["province_id" => 11, "name" => "Kabupaten Tasikmalaya", "kode_kabupaten_kota" => "3206"],
                ["province_id" => 11, "name" => "Kabupaten Ciamis", "kode_kabupaten_kota" => "3207"],
                ["province_id" => 11, "name" => "Kabupaten Kuningan", "kode_kabupaten_kota" => "3208"],
                ["province_id" => 11, "name" => "Kabupaten Cirebon", "kode_kabupaten_kota" => "3209"],
                ["province_id" => 11, "name" => "Kabupaten Majalengka", "kode_kabupaten_kota" => "3210"],
                ["province_id" => 11, "name" => "Kabupaten Sumedang", "kode_kabupaten_kota" => "3211"],
                ["province_id" => 11, "name" => "Kabupaten Indramayu", "kode_kabupaten_kota" => "3212"],
                ["province_id" => 11, "name" => "Kabupaten Subang", "kode_kabupaten_kota" => "3213"],
                ["province_id" => 11, "name" => "Kabupaten Purwakarta", "kode_kabupaten_kota" => "3214"],
                ["province_id" => 11, "name" => "Kabupaten Karawang", "kode_kabupaten_kota" => "3215"],
                ["province_id" => 11, "name" => "Kabupaten Bekasi", "kode_kabupaten_kota" => "3216"],
                ["province_id" => 11, "name" => "Kabupaten Bandung Barat", "kode_kabupaten_kota" => "3217"],
                ["province_id" => 11, "name" => "Kota Bogor", "kode_kabupaten_kota" => "3271"],
                ["province_id" => 11, "name" => "Kota Sukabumi", "kode_kabupaten_kota" => "3272"],
                ["province_id" => 11, "name" => "Kota Bandung", "kode_kabupaten_kota" => "3273"],
                ["province_id" => 11, "name" => "Kota Cirebon", "kode_kabupaten_kota" => "3274"],
                ["province_id" => 11, "name" => "Kota Bekasi", "kode_kabupaten_kota" => "3275"],
                ["province_id" => 11, "name" => "Kota Depok", "kode_kabupaten_kota" => "3276"],
                ["province_id" => 11, "name" => "Kota Cimahi", "kode_kabupaten_kota" => "3277"],
                ["province_id" => 11, "name" => "Kota Tasikmalaya", "kode_kabupaten_kota" => "3278"],
                ["province_id" => 11, "name" => "Kota Banjar", "kode_kabupaten_kota" => "3279"],

                ["province_id" => 12, "nama" => "Kabupaten Cilacap", "kode_kabupaten_kota" => "3301"],
                ["province_id" => 12, "nama" => "Kabupaten Banyumas", "kode_kabupaten_kota" => "3302"],
                ["province_id" => 12, "nama" => "Kabupaten Purbalingga", "kode_kabupaten_kota" => "3303"],
                ["province_id" => 12, "nama" => "Kabupaten Banjarnegara", "kode_kabupaten_kota" => "3304"],
                ["province_id" => 12, "nama" => "Kabupaten Kebumen", "kode_kabupaten_kota" => "3305"],
                ["province_id" => 12, "nama" => "Kabupaten Purworejo", "kode_kabupaten_kota" => "3306"],
                ["province_id" => 12, "nama" => "Kabupaten Wonosobo", "kode_kabupaten_kota" => "3307"],
                ["province_id" => 12, "nama" => "Kabupaten Magelang", "kode_kabupaten_kota" => "3308"],
                ["province_id" => 12, "nama" => "Kabupaten Boyolali", "kode_kabupaten_kota" => "3309"],
                ["province_id" => 12, "nama" => "Kabupaten Klaten", "kode_kabupaten_kota" => "3310"],
                ["province_id" => 12, "nama" => "Kabupaten Sukoharjo", "kode_kabupaten_kota" => "3311"],
                ["province_id" => 12, "nama" => "Kabupaten Wonogiri", "kode_kabupaten_kota" => "3312"],
                ["province_id" => 12, "nama" => "Kabupaten Karanganyar", "kode_kabupaten_kota" => "3313"],
                ["province_id" => 12, "nama" => "Kabupaten Sragen", "kode_kabupaten_kota" => "3314"],
                ["province_id" => 12, "nama" => "Kabupaten Grobogan", "kode_kabupaten_kota" => "3315"],
                ["province_id" => 12, "nama" => "Kabupaten Blora", "kode_kabupaten_kota" => "3316"],
                ["province_id" => 12, "nama" => "Kabupaten Rembang", "kode_kabupaten_kota" => "3317"],
                ["province_id" => 12, "nama" => "Kabupaten Pati", "kode_kabupaten_kota" => "3318"],
                ["province_id" => 12, "nama" => "Kabupaten Kudus", "kode_kabupaten_kota" => "3319"],
                ["province_id" => 12, "nama" => "Kabupaten Jepara", "kode_kabupaten_kota" => "3320"],
                ["province_id" => 12, "nama" => "Kabupaten Demak", "kode_kabupaten_kota" => "3321"],
                ["province_id" => 12, "nama" => "Kabupaten Semarang", "kode_kabupaten_kota" => "3322"],
                ["province_id" => 12, "nama" => "Kabupaten Temanggung", "kode_kabupaten_kota" => "3323"],
                ["province_id" => 12, "nama" => "Kabupaten Kendal", "kode_kabupaten_kota" => "3324"],
                ["province_id" => 12, "nama" => "Kabupaten Batang", "kode_kabupaten_kota" => "3325"],
                ["province_id" => 12, "nama" => "Kabupaten Pekalongan", "kode_kabupaten_kota" => "3326"],
                ["province_id" => 12, "nama" => "Kabupaten Pemalang", "kode_kabupaten_kota" => "3327"],
                ["province_id" => 12, "nama" => "Kabupaten Tegal", "kode_kabupaten_kota" => "3328"],
                ["province_id" => 12, "nama" => "Kabupaten Brebes", "kode_kabupaten_kota" => "3329"],
                ["province_id" => 12, "nama" => "Kota Magelang", "kode_kabupaten_kota" => "3371"],
                ["province_id" => 12, "nama" => "Kota Surakarta", "kode_kabupaten_kota" => "3372"],
                ["province_id" => 12, "nama" => "Kota Salatiga", "kode_kabupaten_kota" => "3373"],
                ["province_id" => 12, "nama" => "Kota Semarang", "kode_kabupaten_kota" => "3374"],
                ["province_id" => 12, "nama" => "Kota Pekalongan", "kode_kabupaten_kota" => "3375"],
                ["province_id" => 12, "nama" => "Kota Tegal", "kode_kabupaten_kota" => "3376"],

                ["province_id" => 13, "nama" => "Kabupaten Kulon Progo", "kode_kabupaten_kota" => "3401"],
                ["province_id" => 13, "nama" => "Kabupaten Bantul", "kode_kabupaten_kota" => "3402"],
                ["province_id" => 13, "nama" => "Kabupaten Gunungkidul", "kode_kabupaten_kota" => "3403"],
                ["province_id" => 13, "nama" => "Kabupaten Sleman", "kode_kabupaten_kota" => "3404"],
                ["province_id" => 13, "nama" => "Kota Yogyakarta", "kode_kabupaten_kota" => "3471"],

                ["province_id" => 14, "nama" => "Kabupaten Pacitan", "kode_kabupaten_kota" => "3501"],
                ["province_id" => 14, "nama" => "Kabupaten Ponorogo", "kode_kabupaten_kota" => "3502"],
                ["province_id" => 14, "nama" => "Kabupaten Trenggalek", "kode_kabupaten_kota" => "3503"],
                ["province_id" => 14, "nama" => "Kabupaten Tulungagung", "kode_kabupaten_kota" => "3504"],
                ["province_id" => 14, "nama" => "Kabupaten Blitar", "kode_kabupaten_kota" => "3505"],
                ["province_id" => 14, "nama" => "Kabupaten Kediri", "kode_kabupaten_kota" => "3506"],
                ["province_id" => 14, "nama" => "Kabupaten Malang", "kode_kabupaten_kota" => "3507"],
                ["province_id" => 14, "nama" => "Kabupaten Lumajang", "kode_kabupaten_kota" => "3508"],
                ["province_id" => 14, "nama" => "Kabupaten Jember", "kode_kabupaten_kota" => "3509"],
                ["province_id" => 14, "nama" => "Kabupaten Banyuwangi", "kode_kabupaten_kota" => "3510"],
                ["province_id" => 14, "nama" => "Kabupaten Bondowoso", "kode_kabupaten_kota" => "3511"],
                ["province_id" => 14, "nama" => "Kabupaten Situbondo", "kode_kabupaten_kota" => "3512"],
                ["province_id" => 14, "nama" => "Kabupaten Probolinggo", "kode_kabupaten_kota" => "3513"],
                ["province_id" => 14, "nama" => "Kabupaten Pasuruan", "kode_kabupaten_kota" => "3514"],
                ["province_id" => 14, "nama" => "Kabupaten Sidoarjo", "kode_kabupaten_kota" => "3515"],
                ["province_id" => 14, "nama" => "Kabupaten Mojokerto", "kode_kabupaten_kota" => "3516"],
                ["province_id" => 14, "nama" => "Kabupaten Jombang", "kode_kabupaten_kota" => "3517"],
                ["province_id" => 14, "nama" => "Kabupaten Nganjuk", "kode_kabupaten_kota" => "3518"],
                ["province_id" => 14, "nama" => "Kabupaten Madiun", "kode_kabupaten_kota" => "3519"],
                ["province_id" => 14, "nama" => "Kabupaten Magetan", "kode_kabupaten_kota" => "3520"],
                ["province_id" => 14, "nama" => "Kabupaten Ngawi", "kode_kabupaten_kota" => "3521"],
                ["province_id" => 14, "nama" => "Kabupaten Bojonegoro", "kode_kabupaten_kota" => "3522"],
                ["province_id" => 14, "nama" => "Kabupaten Tuban", "kode_kabupaten_kota" => "3523"],
                ["province_id" => 14, "nama" => "Kabupaten Lamongan", "kode_kabupaten_kota" => "3524"],
                ["province_id" => 14, "nama" => "Kabupaten Gresik", "kode_kabupaten_kota" => "3525"],
                ["province_id" => 14, "nama" => "Kabupaten Bangkalan", "kode_kabupaten_kota" => "3526"],
                ["province_id" => 14, "nama" => "Kabupaten Sampang", "kode_kabupaten_kota" => "3527"],
                ["province_id" => 14, "nama" => "Kabupaten Pamekasan", "kode_kabupaten_kota" => "3528"],
                ["province_id" => 14, "nama" => "Kabupaten Sumenep", "kode_kabupaten_kota" => "3529"],
                ["province_id" => 14, "nama" => "Kota Kediri", "kode_kabupaten_kota" => "3571"],
                ["province_id" => 14, "nama" => "Kota Blitar", "kode_kabupaten_kota" => "3572"],
                ["province_id" => 14, "nama" => "Kota Malang", "kode_kabupaten_kota" => "3573"],
                ["province_id" => 14, "nama" => "Kota Probolinggo", "kode_kabupaten_kota" => "3574"],
                ["province_id" => 14, "nama" => "Kota Pasuruan", "kode_kabupaten_kota" => "3575"],
                ["province_id" => 14, "nama" => "Kota Mojokerto", "kode_kabupaten_kota" => "3576"],
                ["province_id" => 14, "nama" => "Kota Madiun", "kode_kabupaten_kota" => "3577"],
                ["province_id" => 14, "nama" => "Kota Surabaya", "kode_kabupaten_kota" => "3578"],
                ["province_id" => 14, "nama" => "Kota Batu", "kode_kabupaten_kota" => "3579"],

                ["province_id" => 15, "nama" => "Kabupaten Pandeglang", "kode_kabupaten_kota" => "3601"],
                ["province_id" => 15, "nama" => "Kabupaten Lebak", "kode_kabupaten_kota" => "3602"],
                ["province_id" => 15, "nama" => "Kabupaten Tangerang", "kode_kabupaten_kota" => "3603"],
                ["province_id" => 15, "nama" => "Kabupaten Serang", "kode_kabupaten_kota" => "3604"],
                ["province_id" => 15, "nama" => "Kota Tangerang", "kode_kabupaten_kota" => "3671"],
                ["province_id" => 15, "nama" => "Kota Cilegon", "kode_kabupaten_kota" => "3672"],
                ["province_id" => 15, "nama" => "Kota Serang", "kode_kabupaten_kota" => "3673"],
                ["province_id" => 15, "nama" => "Kota Tangerang Selatan", "kode_kabupaten_kota" => "3674"],

                ["province_id" => 16, "name" => "Kabupaten Jembrana", "kode_kabupaten_kota" => "5101"],
                ["province_id" => 16, "name" => "Kabupaten Tabanan", "kode_kabupaten_kota" => "5102"],
                ["province_id" => 16, "name" => "Kabupaten Badung", "kode_kabupaten_kota" => "5103"],
                ["province_id" => 16, "name" => "Kabupaten Gianyar", "kode_kabupaten_kota" => "5104"],
                ["province_id" => 16, "name" => "Kabupaten Klungkung", "kode_kabupaten_kota" => "5105"],
                ["province_id" => 16, "name" => "Kabupaten Bangli", "kode_kabupaten_kota" => "5106"],
                ["province_id" => 16, "name" => "Kabupaten Karangasem", "kode_kabupaten_kota" => "5107"],
                ["province_id" => 16, "name" => "Kabupaten Buleleng", "kode_kabupaten_kota" => "5108"],
                ["province_id" => 16, "name" => "Kota Denpasar", "kode_kabupaten_kota" => "5171"],


                ["province_id" => 17, "nama" => "Kabupaten Lombok Barat", "kode_kabupaten_kota" => "5201"],
                ["province_id" => 17, "nama" => "Kabupaten Lombok Tengah", "kode_kabupaten_kota" => "5202"],
                ["province_id" => 17, "nama" => "Kabupaten Lombok Timur", "kode_kabupaten_kota" => "5203"],
                ["province_id" => 17, "nama" => "Kabupaten Sumbawa", "kode_kabupaten_kota" => "5204"],
                ["province_id" => 17, "nama" => "Kabupaten Dompu", "kode_kabupaten_kota" => "5205"],
                ["province_id" => 17, "nama" => "Kabupaten Bima", "kode_kabupaten_kota" => "5206"],
                ["province_id" => 17, "nama" => "Kabupaten Sumbawa Barat", "kode_kabupaten_kota" => "5207"],
                ["province_id" => 17, "nama" => "Kota Mataram", "kode_kabupaten_kota" => "5271"],
                ["province_id" => 17, "nama" => "Kota Bima", "kode_kabupaten_kota" => "5272"],

                ["province_id" => 18, "nama" => "Kabupaten Kupang", "kode_kabupaten_kota" => "5301"],
                ["province_id" => 18, "nama" => "Kabupaten Timor Tengah Selatan", "kode_kabupaten_kota" => "5302"],
                ["province_id" => 18, "nama" => "Kabupaten Timor Tengah Utara", "kode_kabupaten_kota" => "5303"],
                ["province_id" => 18, "nama" => "Kabupaten Belu", "kode_kabupaten_kota" => "5304"],
                ["province_id" => 18, "nama" => "Kabupaten Alor", "kode_kabupaten_kota" => "5305"],
                ["province_id" => 18, "nama" => "Kabupaten Flores Timur", "kode_kabupaten_kota" => "5306"],
                ["province_id" => 18, "nama" => "Kabupaten Sikka", "kode_kabupaten_kota" => "5307"],
                ["province_id" => 18, "nama" => "Kabupaten Ende", "kode_kabupaten_kota" => "5308"],
                ["province_id" => 18, "nama" => "Kabupaten Ngada", "kode_kabupaten_kota" => "5309"],
                ["province_id" => 18, "nama" => "Kabupaten Manggarai", "kode_kabupaten_kota" => "5310"],
                ["province_id" => 18, "nama" => "Kabupaten Rote Ndao", "kode_kabupaten_kota" => "5311"],
                ["province_id" => 18, "nama" => "Kabupaten Manggarai Barat", "kode_kabupaten_kota" => "5312"],
                ["province_id" => 18, "nama" => "Kabupaten Sumba Timur", "kode_kabupaten_kota" => "5313"],
                ["province_id" => 18, "nama" => "Kabupaten Sumba Barat", "kode_kabupaten_kota" => "5314"],
                ["province_id" => 18, "nama" => "Kabupaten Lembata", "kode_kabupaten_kota" => "5315"],
                ["province_id" => 18, "nama" => "Kabupaten Sumba Tengah", "kode_kabupaten_kota" => "5316"],
                ["province_id" => 18, "nama" => "Kabupaten Sumba Barat Daya", "kode_kabupaten_kota" => "5317"],
                ["province_id" => 18, "nama" => "Kabupaten Nagekeo", "kode_kabupaten_kota" => "5318"],
                ["province_id" => 18, "nama" => "Kabupaten Manggarai Timur", "kode_kabupaten_kota" => "5319"],
                ["province_id" => 18, "nama" => "Kota Kupang", "kode_kabupaten_kota" => "5371"],

                ["province_id" => 19, "nama" => "Kabupaten Sambas", "kode_kabupaten_kota" => "6101"],
                ["province_id" => 19, "nama" => "Kabupaten Mempawah", "kode_kabupaten_kota" => "6102"],
                ["province_id" => 19, "nama" => "Kabupaten Sanggau", "kode_kabupaten_kota" => "6103"],
                ["province_id" => 19, "nama" => "Kabupaten Ketapang", "kode_kabupaten_kota" => "6104"],
                ["province_id" => 19, "nama" => "Kabupaten Sintang", "kode_kabupaten_kota" => "6105"],
                ["province_id" => 19, "nama" => "Kabupaten Kapuas Hulu", "kode_kabupaten_kota" => "6106"],
                ["province_id" => 19, "nama" => "Kabupaten Bengkayang", "kode_kabupaten_kota" => "6107"],
                ["province_id" => 19, "nama" => "Kabupaten Landak", "kode_kabupaten_kota" => "6108"],
                ["province_id" => 19, "nama" => "Kabupaten Sekadau", "kode_kabupaten_kota" => "6109"],
                ["province_id" => 19, "nama" => "Kabupaten Melawi", "kode_kabupaten_kota" => "6110"],
                ["province_id" => 19, "nama" => "Kabupaten Kayong Utara", "kode_kabupaten_kota" => "6111"],
                ["province_id" => 19, "nama" => "Kabupaten Kubu Raya", "kode_kabupaten_kota" => "6112"],
                ["province_id" => 19, "nama" => "Kota Pontianak", "kode_kabupaten_kota" => "6171"],
                ["province_id" => 19, "nama" => "Kota Singkawang", "kode_kabupaten_kota" => "6172"],

                ["province_id" => 20, "nama" => "Kabupaten Kotawaringin Barat", "kode_kabupaten_kota" => "6201"],
                ["province_id" => 20, "nama" => "Kabupaten Kotawaringin Timur", "kode_kabupaten_kota" => "6202"],
                ["province_id" => 20, "nama" => "Kabupaten Kapuas", "kode_kabupaten_kota" => "6203"],
                ["province_id" => 20, "nama" => "Kabupaten Barito Selatan", "kode_kabupaten_kota" => "6204"],
                ["province_id" => 20, "nama" => "Kabupaten Barito Utara", "kode_kabupaten_kota" => "6205"],
                ["province_id" => 20, "nama" => "Kabupaten Sukamara", "kode_kabupaten_kota" => "6206"],
                ["province_id" => 20, "nama" => "Kabupaten Lamandau", "kode_kabupaten_kota" => "6207"],
                ["province_id" => 20, "nama" => "Kabupaten Seruyan", "kode_kabupaten_kota" => "6208"],
                ["province_id" => 20, "nama" => "Kabupaten Katingan", "kode_kabupaten_kota" => "6209"],
                ["province_id" => 20, "nama" => "Kabupaten Pulang Pisau", "kode_kabupaten_kota" => "6210"],
                ["province_id" => 20, "nama" => "Kabupaten Gunung Mas", "kode_kabupaten_kota" => "6211"],
                ["province_id" => 20, "nama" => "Kabupaten Barito Timur", "kode_kabupaten_kota" => "6212"],
                ["province_id" => 20, "nama" => "Kabupaten Murung Raya", "kode_kabupaten_kota" => "6213"],
                ["province_id" => 20, "nama" => "Kota Palangka Raya", "kode_kabupaten_kota" => "6271"],

                ["province_id" => 21, "nama" => "Kabupaten Tanah Laut", "kode_kabupaten_kota" => "6301"],
                ["province_id" => 21, "nama" => "Kabupaten Kota Baru", "kode_kabupaten_kota" => "6302"],
                ["province_id" => 21, "nama" => "Kabupaten Banjar", "kode_kabupaten_kota" => "6303"],
                ["province_id" => 21, "nama" => "Kabupaten Barito Kuala", "kode_kabupaten_kota" => "6304"],
                ["province_id" => 21, "nama" => "Kabupaten Tapin", "kode_kabupaten_kota" => "6305"],
                ["province_id" => 21, "nama" => "Kabupaten Hulu Sungai Selatan", "kode_kabupaten_kota" => "6306"],
                ["province_id" => 21, "nama" => "Kabupaten Hulu Sungai Tengah", "kode_kabupaten_kota" => "6307"],
                ["province_id" => 21, "nama" => "Kabupaten Hulu Sungai Utara", "kode_kabupaten_kota" => "6308"],
                ["province_id" => 21, "nama" => "Kabupaten Tabalong", "kode_kabupaten_kota" => "6309"],
                ["province_id" => 21, "nama" => "Kabupaten Tanah Bumbu", "kode_kabupaten_kota" => "6310"],
                ["province_id" => 21, "nama" => "Kabupaten Balangan", "kode_kabupaten_kota" => "6311"],
                ["province_id" => 21, "nama" => "Kota Banjarmasin", "kode_kabupaten_kota" => "6371"],
                ["province_id" => 21, "nama" => "Kota Banjarbaru", "kode_kabupaten_kota" => "6372"],

                ["province_id" => 22, "nama" => "Kabupaten Paser", "kode_kabupaten_kota" => "6401"],
                ["province_id" => 22, "nama" => "Kabupaten Kutai Barat", "kode_kabupaten_kota" => "6402"],
                ["province_id" => 22, "nama" => "Kabupaten Kutai Kartanegara", "kode_kabupaten_kota" => "6403"],
                ["province_id" => 22, "nama" => "Kabupaten Kutai Timur", "kode_kabupaten_kota" => "6404"],
                ["province_id" => 22, "nama" => "Kabupaten Berau", "kode_kabupaten_kota" => "6405"],
                ["province_id" => 22, "nama" => "Kabupaten Penajam Paser Utara", "kode_kabupaten_kota" => "6409"],
                ["province_id" => 22, "nama" => "Kota Balikpapan", "kode_kabupaten_kota" => "6471"],
                ["province_id" => 22, "nama" => "Kota Samarinda", "kode_kabupaten_kota" => "6472"],
                ["province_id" => 22, "nama" => "Kota Bontang", "kode_kabupaten_kota" => "6474"],

                ["province_id" => 23, "name" => "Kabupaten Bolaang Mongondow", "kode_kabupaten_kota" => "7101"],
                ["province_id" => 23, "name" => "Kabupaten Minahasa", "kode_kabupaten_kota" => "7102"],
                ["province_id" => 23, "name" => "Kabupaten Kepulauan Sangihe", "kode_kabupaten_kota" => "7103"],
                ["province_id" => 23, "name" => "Kabupaten Kepulauan Talaud", "kode_kabupaten_kota" => "7104"],
                ["province_id" => 23, "name" => "Kabupaten Minahasa Selatan", "kode_kabupaten_kota" => "7105"],
                ["province_id" => 23, "name" => "Kabupaten Minahasa Utara", "kode_kabupaten_kota" => "7106"],
                ["province_id" => 23, "name" => "Kabupaten Bolaang Mongondow Utara", "kode_kabupaten_kota" => "7107"],
                ["province_id" => 23, "name" => "Kabupaten Kepulauan Siau Tagulandang Biaro", "kode_kabupaten_kota" => "7108"],
                ["province_id" => 23, "name" => "Kabupaten Bolaang Mongondow Timur", "kode_kabupaten_kota" => "7109"],
                ["province_id" => 23, "name" => "Kabupaten Bolaang Mongondow Selatan", "kode_kabupaten_kota" => "7110"],
                ["province_id" => 23, "name" => "Kota Manado", "kode_kabupaten_kota" => "7171"],
                ["province_id" => 23, "name" => "Kota Bitung", "kode_kabupaten_kota" => "7172"],
                ["province_id" => 23, "name" => "Kota Tomohon", "kode_kabupaten_kota" => "7173"],
                ["province_id" => 23, "name" => "Kota Kotamobagu", "kode_kabupaten_kota" => "7174"],

                ["province_id" => 24, "name" => "Kabupaten Banggai", "kode_kabupaten_kota" => "7201"],
                ["province_id" => 24, "name" => "Kabupaten Poso", "kode_kabupaten_kota" => "7202"],
                ["province_id" => 24, "name" => "Kabupaten Donggala", "kode_kabupaten_kota" => "7203"],
                ["province_id" => 24, "name" => "Kabupaten Toli-Toli", "kode_kabupaten_kota" => "7204"],
                ["province_id" => 24, "name" => "Kabupaten Buol", "kode_kabupaten_kota" => "7205"],
                ["province_id" => 24, "name" => "Kabupaten Morowali", "kode_kabupaten_kota" => "7206"],
                ["province_id" => 24, "name" => "Kabupaten Banggai Kepulauan", "kode_kabupaten_kota" => "7207"],
                ["province_id" => 24, "name" => "Kabupaten Parigi Moutong", "kode_kabupaten_kota" => "7208"],
                ["province_id" => 24, "name" => "Kabupaten Tojo Una-Una", "kode_kabupaten_kota" => "7209"],
                ["province_id" => 24, "name" => "Kabupaten Sigi", "kode_kabupaten_kota" => "7210"],
                ["province_id" => 24, "name" => "Kabupaten Banggai Laut", "kode_kabupaten_kota" => "7211"],
                ["province_id" => 24, "name" => "Kabupaten Morowali Utara", "kode_kabupaten_kota" => "7212"],
                ["province_id" => 24, "name" => "Kota Palu", "kode_kabupaten_kota" => "7271"],

                ["province_id" => 25, "name" => "Kabupaten Kepulauan Selayar", "kode_kabupaten_kota" => "7301"],
                ["province_id" => 25, "name" => "Kabupaten Bulukumba", "kode_kabupaten_kota" => "7302"],
                ["province_id" => 25, "name" => "Kabupaten Bantaeng", "kode_kabupaten_kota" => "7303"],
                ["province_id" => 25, "name" => "Kabupaten Jeneponto", "kode_kabupaten_kota" => "7304"],
                ["province_id" => 25, "name" => "Kabupaten Takalar", "kode_kabupaten_kota" => "7305"],
                ["province_id" => 25, "name" => "Kabupaten Gowa", "kode_kabupaten_kota" => "7306"],
                ["province_id" => 25, "name" => "Kabupaten Sinjai", "kode_kabupaten_kota" => "7307"],
                ["province_id" => 25, "name" => "Kabupaten Maros", "kode_kabupaten_kota" => "7308"],
                ["province_id" => 25, "name" => "Kabupaten Pangkajene dan Kepulauan", "kode_kabupaten_kota" => "7309"],
                ["province_id" => 25, "name" => "Kabupaten Barru", "kode_kabupaten_kota" => "7310"],
                ["province_id" => 25, "name" => "Kabupaten Bone", "kode_kabupaten_kota" => "7311"],
                ["province_id" => 25, "name" => "Kabupaten Soppeng", "kode_kabupaten_kota" => "7312"],
                ["province_id" => 25, "name" => "Kabupaten Wajo", "kode_kabupaten_kota" => "7313"],
                ["province_id" => 25, "name" => "Kabupaten Sidenreng Rappang", "kode_kabupaten_kota" => "7314"],
                ["province_id" => 25, "name" => "Kabupaten Pinrang", "kode_kabupaten_kota" => "7315"],
                ["province_id" => 25, "name" => "Kabupaten Enrekang", "kode_kabupaten_kota" => "7316"],
                ["province_id" => 25, "name" => "Kabupaten Luwu", "kode_kabupaten_kota" => "7317"],
                ["province_id" => 25, "name" => "Kabupaten Tana Toraja", "kode_kabupaten_kota" => "7318"],
                ["province_id" => 25, "name" => "Kabupaten Luwu Utara", "kode_kabupaten_kota" => "7322"],
                ["province_id" => 25, "name" => "Kabupaten Luwu Timur", "kode_kabupaten_kota" => "7324"],
                ["province_id" => 25, "name" => "Kabupaten Toraja Utara", "kode_kabupaten_kota" => "7326"],
                ["province_id" => 25, "name" => "Kota Makassar", "kode_kabupaten_kota" => "7371"],
                ["province_id" => 25, "name" => "Kota Parepare", "kode_kabupaten_kota" => "7372"],
                ["province_id" => 25, "name" => "Kota Palopo", "kode_kabupaten_kota" => "7373"],

                ["province_id" => 26, "name" => "Kabupaten Buton", "kode_kabupaten_kota" => "7401"],
                ["province_id" => 26, "name" => "Kabupaten Muna", "kode_kabupaten_kota" => "7402"],
                ["province_id" => 26, "name" => "Kabupaten Konawe", "kode_kabupaten_kota" => "7403"],
                ["province_id" => 26, "name" => "Kabupaten Kolaka", "kode_kabupaten_kota" => "7404"],
                ["province_id" => 26, "name" => "Kabupaten Konawe Selatan", "kode_kabupaten_kota" => "7405"],
                ["province_id" => 26, "name" => "Kabupaten Bombana", "kode_kabupaten_kota" => "7406"],
                ["province_id" => 26, "name" => "Kabupaten Wakatobi", "kode_kabupaten_kota" => "7407"],
                ["province_id" => 26, "name" => "Kabupaten Kolaka Utara", "kode_kabupaten_kota" => "7408"],
                ["province_id" => 26, "name" => "Kabupaten Konawe Utara", "kode_kabupaten_kota" => "7409"],
                ["province_id" => 26, "name" => "Kabupaten Buton Utara", "kode_kabupaten_kota" => "7410"],
                ["province_id" => 26, "name" => "Kabupaten Kolaka Timur", "kode_kabupaten_kota" => "7411"],
                ["province_id" => 26, "name" => "Kabupaten Konawe Kepulauan", "kode_kabupaten_kota" => "7412"],
                ["province_id" => 26, "name" => "Kabupaten Muna Barat", "kode_kabupaten_kota" => "7413"],
                ["province_id" => 26, "name" => "Kabupaten Buton Tengah", "kode_kabupaten_kota" => "7414"],
                ["province_id" => 26, "name" => "Kabupaten Buton Selatan", "kode_kabupaten_kota" => "7415"],
                ["province_id" => 26, "name" => "Kota Kendari", "kode_kabupaten_kota" => "7471"],
                ["province_id" => 26, "name" => "Kota Baubau", "kode_kabupaten_kota" => "7472"],

                ["province_id" => 27, "name" => "Kabupaten Boalemo", "kode_kabupaten_kota" => "7501"],
                ["province_id" => 27, "name" => "Kabupaten Gorontalo", "kode_kabupaten_kota" => "7502"],
                ["province_id" => 27, "name" => "Kabupaten Pohuwato", "kode_kabupaten_kota" => "7503"],
                ["province_id" => 27, "name" => "Kabupaten Bone Bolango", "kode_kabupaten_kota" => "7504"],
                ["province_id" => 27, "name" => "Kabupaten Gorontalo Utara", "kode_kabupaten_kota" => "7505"],
                ["province_id" => 27, "name" => "Kota Gorontalo", "kode_kabupaten_kota" => "7571"],


                ["province_id" => 28, "name" => "Kabupaten Majene", "kode_kabupaten_kota" => "7601"],
                ["province_id" => 28, "name" => "Kabupaten Polewali Mandar", "kode_kabupaten_kota" => "7602"],
                ["province_id" => 28, "name" => "Kabupaten Mamasa", "kode_kabupaten_kota" => "7603"],
                ["province_id" => 28, "name" => "Kabupaten Mamuju", "kode_kabupaten_kota" => "7604"],
                ["province_id" => 28, "name" => "Kabupaten Mamuju Utara", "kode_kabupaten_kota" => "7605"],
                ["province_id" => 28, "name" => "Kabupaten Mamuju Tengah", "kode_kabupaten_kota" => "7606"],

                ["province_id" => 29, "name" => "Kabupaten Maluku Tengah", "kode_kabupaten_kota" => "8101"],
                ["province_id" => 29, "name" => "Kabupaten Buru", "kode_kabupaten_kota" => "8102"],
                ["province_id" => 29, "name" => "Kabupaten Seram Bagian Timur", "kode_kabupaten_kota" => "8103"],
                ["province_id" => 29, "name" => "Kabupaten Seram Bagian Barat", "kode_kabupaten_kota" => "8104"],
                ["province_id" => 29, "name" => "Kabupaten Kepulauan Aru", "kode_kabupaten_kota" => "8105"],
                ["province_id" => 29, "name" => "Kabupaten Maluku Barat Daya", "kode_kabupaten_kota" => "8106"],
                ["province_id" => 29, "name" => "Kabupaten Buru Selatan", "kode_kabupaten_kota" => "8107"],
                ["province_id" => 29, "name" => "Kota Ambon", "kode_kabupaten_kota" => "8171"],
                ["province_id" => 29, "name" => "Kota Tual", "kode_kabupaten_kota" => "8172"],

                ["province_id" => 30, "name" => "Kabupaten Halmahera Barat", "kode_kabupaten_kota" => "8201"],
                ["province_id" => 30, "name" => "Kabupaten Halmahera Tengah", "kode_kabupaten_kota" => "8202"],
                ["province_id" => 30, "name" => "Kabupaten Halmahera Utara", "kode_kabupaten_kota" => "8203"],
                ["province_id" => 30, "name" => "Kabupaten Halmahera Selatan", "kode_kabupaten_kota" => "8204"],
                ["province_id" => 30, "name" => "Kabupaten Kepulauan Sula", "kode_kabupaten_kota" => "8205"],
                ["province_id" => 30, "name" => "Kabupaten Halmahera Timur", "kode_kabupaten_kota" => "8206"],
                ["province_id" => 30, "name" => "Kabupaten Pulau Morotai", "kode_kabupaten_kota" => "8207"],
                ["province_id" => 30, "name" => "Kota Ternate", "kode_kabupaten_kota" => "8271"],
                ["province_id" => 30, "name" => "Kota Tidore Kepulauan", "kode_kabupaten_kota" => "8272"],

                ["province_id" => 31, "name" => "Kabupaten Merauke", "kode_kabupaten_kota" => "9101"],
                ["province_id" => 31, "name" => "Kabupaten Jayawijaya", "kode_kabupaten_kota" => "9102"],
                ["province_id" => 31, "name" => "Kabupaten Jayapura", "kode_kabupaten_kota" => "9103"],
                ["province_id" => 31, "name" => "Kabupaten Nabire", "kode_kabupaten_kota" => "9104"],
                ["province_id" => 31, "name" => "Kabupaten Kepulauan Yapen", "kode_kabupaten_kota" => "9105"],
                ["province_id" => 31, "name" => "Kabupaten Biak Numfor", "kode_kabupaten_kota" => "9106"],
                ["province_id" => 31, "name" => "Kabupaten Paniai", "kode_kabupaten_kota" => "9107"],
                ["province_id" => 31, "name" => "Kabupaten Puncak Jaya", "kode_kabupaten_kota" => "9108"],
                ["province_id" => 31, "name" => "Kabupaten Mimika", "kode_kabupaten_kota" => "9109"],
                ["province_id" => 31, "name" => "Kabupaten Boven Digoel", "kode_kabupaten_kota" => "9110"],
                ["province_id" => 31, "name" => "Kabupaten Mappi", "kode_kabupaten_kota" => "9111"],
                ["province_id" => 31, "name" => "Kabupaten Asmat", "kode_kabupaten_kota" => "9112"],
                ["province_id" => 31, "name" => "Kabupaten Yahukimo", "kode_kabupaten_kota" => "9113"],
                ["province_id" => 31, "name" => "Kabupaten Pegunungan Bintang", "kode_kabupaten_kota" => "9114"],
                ["province_id" => 31, "name" => "Kabupaten Tolikara", "kode_kabupaten_kota" => "9115"],
                ["province_id" => 31, "name" => "Kabupaten Sarmi", "kode_kabupaten_kota" => "9116"],
                ["province_id" => 31, "name" => "Kabupaten Keerom", "kode_kabupaten_kota" => "9117"],
                ["province_id" => 31, "name" => "Kabupaten Waropen", "kode_kabupaten_kota" => "9118"],
                ["province_id" => 31, "name" => "Kabupaten Supiori", "kode_kabupaten_kota" => "9119"],
                ["province_id" => 31, "name" => "Kabupaten Mamberamo Raya", "kode_kabupaten_kota" => "9120"],
                ["province_id" => 31, "name" => "Kabupaten Nduga", "kode_kabupaten_kota" => "9121"],
                ["province_id" => 31, "name" => "Kabupaten Lanny Jaya", "kode_kabupaten_kota" => "9122"],
                ["province_id" => 31, "name" => "Kabupaten Mamberamo Tengah", "kode_kabupaten_kota" => "9123"],
                ["province_id" => 31, "name" => "Kabupaten Yalimo", "kode_kabupaten_kota" => "9124"],
                ["province_id" => 31, "name" => "Kabupaten Puncak", "kode_kabupaten_kota" => "9125"],
                ["province_id" => 31, "name" => "Kabupaten Dogiyai", "kode_kabupaten_kota" => "9126"],
                ["province_id" => 31, "name" => "Kabupaten Intan Jaya", "kode_kabupaten_kota" => "9127"],
                ["province_id" => 31, "name" => "Kabupaten Deiyai", "kode_kabupaten_kota" => "9128"],
                ["province_id" => 31, "name" => "Kota Jayapura", "kode_kabupaten_kota" => "9171"],

                ["province_id" => 32, "name" => "Kabupaten Sorong", "kode_kabupaten_kota" => "9201"],
                ["province_id" => 32, "name" => "Kabupaten Sorong Selatan", "kode_kabupaten_kota" => "9202"],
                ["province_id" => 32, "name" => "Kabupaten Manokwari", "kode_kabupaten_kota" => "9203"],
                ["province_id" => 32, "name" => "Kabupaten Fakfak", "kode_kabupaten_kota" => "9204"],
                ["province_id" => 32, "name" => "Kabupaten Kaimana", "kode_kabupaten_kota" => "9205"],
                ["province_id" => 32, "name" => "Kabupaten Teluk Wondama", "kode_kabupaten_kota" => "9206"],
                ["province_id" => 32, "name" => "Kabupaten Teluk Bintuni", "kode_kabupaten_kota" => "9207"],
                ["province_id" => 32, "name" => "Kabupaten Raja Ampat", "kode_kabupaten_kota" => "9208"],
                ["province_id" => 32, "name" => "Kabupaten Tambrauw", "kode_kabupaten_kota" => "9209"],
                ["province_id" => 32, "name" => "Kabupaten Maybrat", "kode_kabupaten_kota" => "9210"],
                ["province_id" => 32, "name" => "Kabupaten Manokwari Selatan", "kode_kabupaten_kota" => "9211"],
                ["province_id" => 32, "name" => "Kabupaten Pegunungan Arfak", "kode_kabupaten_kota" => "9212"],
                ["province_id" => 32, "name" => "Kota Sorong", "kode_kabupaten_kota" => "9271"],


            ]
            // Add more regencies as needed
        );
    }
}
